# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: products.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='products.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eproducts.proto\"V\n\x12SendProductRequest\x12\x13\n\x0bid_producto\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x1b\n\x13\x63\x61ntidad_disponible\x18\x03 \x01(\x05\"G\n\x13SendProductResponse\x12\x13\n\x0bid_producto\x18\x01 \x01(\x05\x12\x1b\n\x13\x63\x61ntidad_disponible\x18\x02 \x01(\x05\x32\x44\n\x08Products\x12\x38\n\x0bSendProduct\x12\x13.SendProductRequest\x1a\x14.SendProductResponseb\x06proto3'
)




_SENDPRODUCTREQUEST = _descriptor.Descriptor(
  name='SendProductRequest',
  full_name='SendProductRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_producto', full_name='SendProductRequest.id_producto', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nombre', full_name='SendProductRequest.nombre', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cantidad_disponible', full_name='SendProductRequest.cantidad_disponible', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=104,
)


_SENDPRODUCTRESPONSE = _descriptor.Descriptor(
  name='SendProductResponse',
  full_name='SendProductResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_producto', full_name='SendProductResponse.id_producto', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cantidad_disponible', full_name='SendProductResponse.cantidad_disponible', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=177,
)

DESCRIPTOR.message_types_by_name['SendProductRequest'] = _SENDPRODUCTREQUEST
DESCRIPTOR.message_types_by_name['SendProductResponse'] = _SENDPRODUCTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SendProductRequest = _reflection.GeneratedProtocolMessageType('SendProductRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDPRODUCTREQUEST,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:SendProductRequest)
  })
_sym_db.RegisterMessage(SendProductRequest)

SendProductResponse = _reflection.GeneratedProtocolMessageType('SendProductResponse', (_message.Message,), {
  'DESCRIPTOR' : _SENDPRODUCTRESPONSE,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:SendProductResponse)
  })
_sym_db.RegisterMessage(SendProductResponse)



_PRODUCTS = _descriptor.ServiceDescriptor(
  name='Products',
  full_name='Products',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=179,
  serialized_end=247,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendProduct',
    full_name='Products.SendProduct',
    index=0,
    containing_service=None,
    input_type=_SENDPRODUCTREQUEST,
    output_type=_SENDPRODUCTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRODUCTS)

DESCRIPTOR.services_by_name['Products'] = _PRODUCTS

# @@protoc_insertion_point(module_scope)
